#! /bin/sh

xrandr --output DP-2 --mode 3840x2160 --rate 144 --primary --output DP-4 --mode 1920x1080 --rate 144 --right-of DP-2

picom &
sxhkd &
xsetroot -cursor_name left_ptr &

bspc wm -O DP-2 DP-4
bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-4 -d 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 6
bspc config focus_follows_pointer true

# floating rules
bspc rule -a Thunar state=floating
bspc rule -a Xarchiver state=floating
bspc rule -a Galculator state=floating
bspc rule -a rars-Launch state=floating
bspc rule -a Pavucontrol state=floating

# launch polybar
$HOME/.config/polybar/launch.sh

# auth agent
lxqt-policykit-agent &

# eq
easyeffects --gapplication-service &

# gpu fan curve and power limit
gwe --hide-window &

feh --bg-scale $HOME/Pictures/Wallpapers/99810.jpg
discord &
